apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: alpine-linux-package-manager-apk-in-image-build-and-deploy-enforce
spec:
  policyName: Alpine Linux Package Manager (apk) in Image - Build and Deploy - Enforce
  description: Alert on deployments with the Alpine Linux package manager (apk) present
  rationale: Package managers make it easier for attackers to use compromised containers, since they can easily add software.
  remediation: Run `apk --purge del apk-tools` in the image build for production containers.
  disabled: false
  categories:
    - Security Best Practices
  lifecycleStages:
    - BUILD
    - DEPLOY
  eventSource: NOT_APPLICABLE
  exclusions:
    - deployment:
        name: master-etcd-openshift-master-.*
        scope:
          namespace: kube-system
    - deployment:
        name: token-refresher
        scope:
          namespace: openshift-monitoring
    - deployment:
        name: csi-azuredisk-node-win
        scope:
          namespace: kube-system
  scope:
    - cluster: 0af04689-c285-4b8b-9718-6699678e1a28
      namespace: patient-portal
  severity: LOW_SEVERITY
  enforcementActions:
    - FAIL_BUILD_ENFORCEMENT
    - SCALE_TO_ZERO_ENFORCEMENT
    - UNSATISFIABLE_NODE_CONSTRAINT_ENFORCEMENT
  policySections:
    - policyGroups:
        - fieldName: Image Component
          booleanOperator: OR
          values:
            - value: apk-tools=
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
